// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("BlocktrailSdk.SampleCSharp")]
[assembly: AssemblyProductAttribute("BlocktrailSdk")]
[assembly: AssemblyDescriptionAttribute("SDK for blocktrail.com")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
